version: "3.9"

services:
  back:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '512M'
        reservations:
          cpus: '0.05'
          memory: '32M'
    image: chsergeig/tg-autoreply:latest
    environment:
      ACTIVE_PROFILE: prod
      API_HASH: '00aaff99'
      API_ID: '000000'
      DB_KEY: 'db-pa$$w0rD'
      DB_LOCATION: /session.sqlite
      DEVICE_MODEL: 'my_telegram'
      SYSTEM_LANG_CODE: 'ru'
      USER_PHONE: '123456 w/o +'
      JAVA_TOOL_OPTIONS: ''
      REPLY_DEFAULT_ENABLED: false
      REPLY_DEFAULT_MESSAGE: 'Im not available now. Read your message ASAP'
      USER_LOGIN: 'very-good-login'
      USER_PASSWORD: 'very-string-paSSwoRd'
    ports:
      - "8080:8080"
    volumes:
      - ./session.sqlite:/session.sqlite
  webserver:
    image: nginx:latest
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx.80.conf:/etc/nginx/conf.d/default.conf
#      - ./nginx.443.conf:/etc/nginx/conf.d/ssl.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot:latest
    depends_on:
      - webserver
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

