name: Publish Docker image

on:
  push:
    branches:
      - main
    paths:
      - .env
      - Dockerfile
      - gradle.properties
      - .github/workflows/docker-publish.yml

jobs:
  build:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for web Docker image
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: chsergeig/tg-autoreply

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          build-args: |
            GH_LOGIN=${{ secrets.GH_LOGIN }}
            GH_TOKEN=${{ secrets.GH_TOKEN }}
          file: ./Dockerfile
          push: true
          tags: chsergeig/tg-autoreply:1.3.0,chsergeig/tg-autoreply:latest
